[build-system]
requires = ["sip >=6, <7"]
build-backend = "sipbuild.api"

[tool.sip.project]
name = "pydmtx"

[tool.sip.metadata]
name = "pydmtx"
version = "0.1"

[tool.sip.bindings.pydmtx]
headers = ["dmtxwrapper/src/dmtxencoderwrapper.h"]
sources = ["dmtxwrapper/src/dmtxencoderwrapper.cpp"]
libraries = ["dmtxwrapper", "dmtx"]
include-dirs = ["dmtxwrapper/src"]
library-dirs = ["bin/libdmtxwrapper"]
